import { METRIC_SETS } from "./types";
import type { RefData } from "./types";

let cache: RefData | null = null;

// Reference data is the single source of truth generated by the R package's
// data-raw pipeline (inst/extdata/web/*.json), copied into public/data.
export async function loadData(): Promise<RefData> {
  if (cache) return cache;
  const base = import.meta.env.BASE_URL;
  const get = (f: string) => fetch(`${base}data/${f}`).then((r) => r.json());
  const metricEntries = await Promise.all(METRIC_SETS.map(async (m) => [
    m.value,
    await get(`metrics_v${m.value}.json`),
  ] as const));
  const metricSets = Object.fromEntries(metricEntries);
  const [licenses, formats, access, protocols] = await Promise.all([
    get("licenses.json"),
    get("file_formats.json"),
    get("access_rights.json"),
    get("standard_protocols.json"),
  ]);
  const metrics = metricSets["0.8"];
  const softwareMetrics = metricSets["0.7_software"];
  cache = { metrics, softwareMetrics, metricSets, licenses, formats, access, protocols };
  return cache;
}
