import { readFileSync } from "node:fs";
import { assess } from "../src/lib/engine";
const DIR = "/Users/choxos/Documents/GitHub/rfuji/webapp/public/data";
const read = (f: string) => JSON.parse(readFileSync(`${DIR}/${f}`, "utf8"));
const data: any = { metrics: read("metrics_v0.8.json"), licenses: read("licenses.json"), formats: read("file_formats.json"), access: read("access_rights.json"), protocols: read("standard_protocols.json") };
const a = await assess(process.argv[2] ?? "https://doi.org/10.5281/zenodo.8347772", data);
const fair = a.summary.find((s: any) => s.category === "FAIR");
console.log("FAIR:", fair.earned + "/" + fair.total, "=", fair.percent + "% | pass", a.results.filter((r: any) => r.status === "pass").length + "/" + a.results.length);
console.log("harvested:", Object.keys(a.metadata).join(", "));
console.log("reuse:", a.reuse.map((r: any) => r.category).join("; ") || "none", "| access:", a.access.access);
