import { readFileSync } from "node:fs";
import { assess } from "../src/lib/engine";
const DIR = "/Users/choxos/Documents/GitHub/rfuji/webapp/public/data";
const read = (f: string) => JSON.parse(readFileSync(`${DIR}/${f}`, "utf8"));
const versions = ["0.8", "0.5", "0.5ssv2", "0.5ss", "0.5env", "0.7_software", "0.7_software_cessda", "0.6a2a", "0.4", "0.3", "0.2"];
const metricSets = Object.fromEntries(versions.map((v) => [v, read(`metrics_v${v}.json`)]));
const data: any = { metrics: metricSets["0.8"], softwareMetrics: metricSets["0.7_software"], metricSets, licenses: read("licenses.json"), formats: read("file_formats.json"), access: read("access_rights.json"), protocols: read("standard_protocols.json") };
const a = await assess(process.argv[2] ?? "https://doi.org/10.5281/zenodo.8347772", data, (process.argv[3] as any) ?? "0.8");
const fair = a.summary.find((s: any) => s.category === "FAIR");
console.log("FAIR:", fair.earned + "/" + fair.total, "=", fair.percent + "% | pass", a.results.filter((r: any) => r.status === "pass").length + "/" + a.results.length);
console.log("harvested:", Object.keys(a.metadata).join(", "));
console.log("reuse:", a.reuse.map((r: any) => r.category).join("; ") || "none", "| access:", a.access.access);
