import type { RefData } from "./types";

let cache: RefData | null = null;

// Reference data is the single source of truth generated by the R package's
// data-raw pipeline (inst/extdata/web/*.json), copied into public/data.
export async function loadData(): Promise<RefData> {
  if (cache) return cache;
  const base = import.meta.env.BASE_URL;
  const get = (f: string) => fetch(`${base}data/${f}`).then((r) => r.json());
  const [metrics, licenses, formats, access, protocols] = await Promise.all([
    get("metrics_v0.8.json"),
    get("licenses.json"),
    get("file_formats.json"),
    get("access_rights.json"),
    get("standard_protocols.json"),
  ]);
  cache = { metrics, licenses, formats, access, protocols };
  return cache;
}
